services:
  - type: web
    name: citabook-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: CLIENT_URL
        sync: false
